### ISSUE TITLE
Unable to upgrade your perceptilabs database.

### ISSUE THREAD

**Issue by CHOU-ZIH** [PerceptiLabs/PerceptiLabs#128]
When I run 'perceptilabs' in anaconda on windows 10, prompt pop out this warning:

Unable to upgrade your perceptilabs database.

And I  follow the official construction run 'perceptilabs -v=3', I got this:

Traceback (most recent call last):
  File "c:\users\chou\anaconda3\envs\perceptilabs\lib\site-packages\django\apps\config.py", line 244, in create
    app_module = import_module(app_name)
  File "c:\users\chou\anaconda3\envs\perceptilabs\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last): 

  File "c:\users\chou\anaconda3\envs\perceptilabs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\chou\anaconda3\envs\perceptilabs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\chou\anaconda3\envs\perceptilabs\lib\site-packages\django\__main__.py", line 9, in <module>
    management.execute_from_command_line()
  File "c:\users\chou\anaconda3\envs\perceptilabs\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "c:\users\chou\anaconda3\envs\perceptilabs\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "c:\users\chou\anaconda3\envs\perceptilabs\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "c:\users\chou\anaconda3\envs\perceptilabs\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "c:\users\chou\anaconda3\envs\perceptilabs\lib\site-packages\django\apps\config.py", line 250, in create
    app_config_class.__qualname__,
django.core.exceptions.ImproperlyConfigured: Cannot import 'api'. Check that 'rygg.api.apps.ApiConfig.name' is correct.
Error: Unable to upgrade your perceptilabs database.

The error is from django, I tried to uninstall and install it, it doesn't work.
Do anyone have good suggestion, thank U so musch!!

**Comment by sethwheway** [comment]
This issue happens due to the latest version of django being incompatible with perceptilabs. `pip install Django==3.1.8` should fix it

**Comment by BalasakthiSS** [comment]
I tried installing the Django version 3.1.8 still facing the same issue :(

**Comment by Bernicetwili** [comment]
> pip instal -U Django==3.1.8
tried this but it is not working

**Comment by AntonOfTheWoods** [comment]
Perceptilabs is not open or with any source I could find. My guess is that they only want it executed in a toy, desktop/laptop environment so you have to purchase their services. That means it works when you run is as some random desktop user but they have deliberately sabotaged it for running in docker, etc.

**Comment by ghostxxz** [comment]
Error: Unable to upgrade your perceptilabs database.
the same issue i am facing right now on my ubuntu machine virtual env.
if anyone have the solution?

**Comment by optroodt** [comment]
Same problem here. I'm trying to run it in a Docker container on an M1 Mac (specifying the `--platform "linux/x86_64/v8"` flag when building my image).

I went into the container and ran `perceptilabs -v 2`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/django/__main__.py", line 9, in <module>
    management.execute_from_command_line()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 213, in close_all
    connection.close()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 282, in close
    if not self.is_in_memory_db():
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 407, in is_in_memory_db
    return self.creation.is_in_memory_db(self.settings_dict['NAME'])
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/creation.py", line 14, in is_in_memory_db
    database_name == ':memory:' or 'mode=memory' in database_name
TypeError: argument of type 'NoneType' is not iterable
Error: Unable to upgrade your perceptilabs database.
```

Seems like Django needs some more configuration.
